#!/usr/bin/env python3
import sys
import os

from censo.cli.interface import entry_point

if __name__ == "__main__":
    sys.path.insert(0, f"{os.path.join(os.path.split(__file__)[0], 'src')}")
    sys.exit(entry_point())
