import os
import shutil
import sys
from os import getcwd
from argparse import ArgumentError

from .cml_parser import parse
from ..configuration import configure, override_rc, homerc
from ..ensembledata import EnsembleData
from ..ensembleopt import Prescreening, Screening, Optimization, Refinement
from ..part import CensoPart
from ..properties import NMR
from ..params import DESCR, __version__
from ..utilities import print, setup_logger

logger = setup_logger(__name__)


def entry_point(argv: list[str] | None = None) -> int:
    """
    Console entry point to execute CENSO from the command line.
    """
    try:
        args = parse(DESCR, argv)
    except ArgumentError as e:
        print(e.message)
        return 1
    except SystemExit:
        return 0

    if not any(vars(args).values()):
        print("CENSO needs at least one argument!")
        return 1

    # Print program call
    print("CALL: " + " ".join(arg for arg in argv))

    ensemble = startup(args)
    if ensemble is None:
        return 0

    # Print general settings once
    CensoPart.print_info()

    run = filter(
        lambda x: x.get_settings()["run"],
        [Prescreening, Screening, Optimization, Refinement, NMR],
    )

    time = 0.0
    for part in run:
        p = part(ensemble)
        runtime = p.run()
        print(f"Ran {p._name} in {runtime} seconds!")
        time += runtime

    print(f"\nTotal timing: {time} seconds")

    print("\nCENSO all done!")
    return 0


# sets up a ensemble object for you using the given cml arguments and censorc
def startup(args) -> EnsembleData | None:
    # get most important infos for current run
    cwd = getcwd()

    # run actions for which no complete setup is needed
    if args.version:
        print(__version__)
        return None
    elif args.cleanup:
        cleanup_run(cwd)
        print("Removed files and going to exit!")
        return None
    elif args.cleanup_all:
        cleanup_run(cwd, complete=True)
        print("Removed files and going to exit!")
        return None
    elif args.writeconfig:
        configure(rcpath=cwd, create_new=True)
        return None
    elif args.inprcpath is not None:
        configure(args.inprcpath)
    # In the case that no inprcpath has been provided assert that the rcfile in the
    # user's home directory exist
    elif args.inprcpath is None:
        assert homerc is True

    # Override settings with command line arguments
    override_rc(args)

    # initialize ensemble, constructor get runinfo from args
    ensemble = EnsembleData(cwd, args=args)

    # read input and setup conformers
    ensemble.read_input(args.inp)

    # END of setup
    # -> ensemble.conformers contains all conformers with their info from input (sorted by CREST energy if possible)

    return ensemble


def cleanup_run(cwd, complete=False):
    """
    Delete all unneeded files.
    """

    # files containing these patterns are deleted
    to_delete = [
        "censo.log",
        "prescreening",
        "screening",
        "optimization",
        "refinement",
        "nmr",
        "uvvis",
    ]

    if complete:
        print("Removing ALL files generated by previous CENSO runs, including ensembles!")

    print(
        f"Be aware that files in {cwd} and subdirectories with names containing the following substrings "
        f"will be deleted:"
    )
    for sub in to_delete:
        print(sub)

    print("Do you wish to continue?")
    print("Please type 'yes' or 'no':")

    ui = input()
    if ui.strip().lower() not in ["yes", "y"]:
        print("Aborting cleanup!")
        sys.exit(0)

    # iterate over files in cwd and subdirs recursively and remove them if to delete
    for subdir, dirs, files in os.walk(cwd):
        if any(s in subdir for s in to_delete):
            print(f"Removing: {subdir}")
            shutil.rmtree(subdir)
        for file in files:
            if any(s in file for s in to_delete) and (complete or "ensemble" not in file):
                print(f"Removing: {file}")
                os.remove(os.path.join(subdir, file))
